name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Generate a project from the template (so CI tests the template, not itself)
      - name: Generate project with Cookiecutter
        run: |
          pip install cookiecutter
          cookiecutter . --no-input project_slug=test_dash project_name="CI Test" description="Check template"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps & run tests
        working-directory: test_dash
        run: |
          make setup
          make fmt          # ensure formatters don't change anything
{% if cookiecutter.include_tests == 'y' -%}
          make test
{%- endif %}

