[tool.black]
line-length = 120
# Use Black's default exclude list and ADD /env/
extend-exclude = '''
/(
    env          # <-- your virtual-env
  | \.direnv
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \.svn
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
  "**/env/*",
  "**/.venv/*",
  "**/.git/*",
  "**/.mypy_cache/*",
  "**/.nox/*",
  "**/.tox/*",
  "**/build/*",
  "**/dist/*",
]
